### ISSUE TITLE
Using generateData, what is difference between passing true or false.

### ISSUE THREAD

**Issue by david-beal** [mathieuancelin/js-repaint-perfs#100]
Hi ! Forgive me for asking this simple question ~ I read the source code, but still confused.

I saw the projects that some use `ENV.generateData(true)` or can use `ENV.generateData(false)` , so what is the mainly difference between passing `true` and `false` ? 

It seems that use `false` repaint is faster than use `true` generateData ? And is using `true` will take up more memory ?

**Comment by mathieuancelin** [comment]
`ENV.generateData(true)` will keep all generated object identities, it is useful with framework like Angular that checks object identity to trigger repaint.

`ENV.generateData(false)` regenerate everything each round.
