### ISSUE TITLE
inline  the results

### ISSUE THREAD

**Issue by mhevery** [mathieuancelin/js-repaint-perfs#21]
Could you update http://mathieuancelin.github.io/js-repaint-perfs/ and have the optimized Angular2 version in the list. (I know it is on the bottom, but a bit confusing.) We would like to feature your test suite on our twitter account, but want to make sure that people can compare apples to apples and don't get confused with the stale information.

**Comment by mathieuancelin** [comment]
Hi @mhevery 

I just changed the style of the landing page. 

I have to admit it's not that pretty, but there is only one list, with color to target optimized or naive version.

Let me know if it's okay for you.
