### ISSUE TITLE
Name "Vanilla optimized" is misleading

### ISSUE THREAD

**Issue by Ginden** [mathieuancelin/js-repaint-perfs#42]
[Vanilla optimized](https://github.com/mathieuancelin/js-repaint-perfs/blob/gh-pages/vanilla-optimized/app.js) in fact is extremely naive approach and should be listed as "vanilla simple 2".

**Comment by mathieuancelin** [comment]
All version of the test are supposed to be 'naive' implementations. 

If not, it's optimized version. In the case of Vanilla optimized (no lib or fwk) it's the non naive version.

Also, the name 'vanilla optimized' doesn't appear on the site
