### ISSUE TITLE
Is Ember dbmon using Glimmer engine?

### ISSUE THREAD

**Issue by lhorie** [mathieuancelin/js-repaint-perfs#57]
It seems... very slow in comparison with everything else

**Comment by mathieuancelin** [comment]
I think it's an old version of ember, 

so if you have any Ember knowledge, PR are welcome ;-)

**Comment by Cryrivers** [comment]
@lhorie No as it's using Ember 1.10.0 which is pretty out-dated and cannot reflect real performance of the latest Ember. ~~I'm trying to re-write the benchmark for Ember.~~

@chilicoder created a PR #97.

**Comment by mathieuancelin** [comment]
Thanks @Cryrivers :-)

**Comment by terinjokes** [comment]
@Cryrivers Have you been successful at updating the comparison?

**Comment by yarigpopov** [comment]
I created a PR #97  for up-to-date version
