### ISSUE TITLE
Aurelia benchmark

### ISSUE THREAD

**Issue by ma3yta** [mathieuancelin/js-repaint-perfs#74]
@mathieuancelin Couild you publish Aurelia benchmark to your site from https://github.com/jdanyow/aurelia-dbmonster/ ?

**Comment by mathieuancelin** [comment]
Hi @Ma3yTa, yes I can publish the Aurelia benchmark. @jdanyow is welcome to open a PR and I will merge it

**Comment by jdanyow** [comment]
@Ma3yTa / @mathieuancelin I'll put a PR together in the next week or so, we have basic and optimized versions we want to add.

cc @martingust @EisenbergEffect

**Comment by claudiobernasconi** [comment]
@jdanyow are you still planning on adding the Aurelia implementation in the future? Is this issue still considered as taken or are you @mathieuancelin open for a PR?

**Comment by jdanyow** [comment]
apologies- I forgot about this. I'll put together a PR
