### ISSUE TITLE
Ripple weird values

### ISSUE THREAD

**Issue by boussou** [mathieuancelin/js-repaint-perfs#76]
Ripple has a setinterval instead of settimeout (like it is with the others). this gives strange values for me (like 200 instead of 30). I changed it to the following:

> function loadSamples() {
>   ripple('databases', ENV.generateData().toArray())
>   Monitoring.renderRate.ping()
>     setTimeout(loadSamples, ENV.timeout);
> }

(I took the code from the ractive version)

Generally speaking, each benchmark should use the same timeout function IMHO

**Comment by mathieuancelin** [comment]
Hi,

that's strange indeed. You can send me a PR to fix the code of the Rippple implementation
